# GitHub Funding configuration
github: [ataca3000]
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom: ['https://www.paypal.me/ataca3000'] # Reemplaza con tu link si tienes uno
