name: Release

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: npm install
      - run: npm run release -- --release-as patch
      - run: git push origin main --follow-tags
